/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package alluxio.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)")
public class BlockConsitencyCheckTResponse implements org.apache.thrift.TBase<BlockConsitencyCheckTResponse, BlockConsitencyCheckTResponse._Fields>, java.io.Serializable, Cloneable, Comparable<BlockConsitencyCheckTResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BlockConsitencyCheckTResponse");

  private static final org.apache.thrift.protocol.TField BLOCK_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("blockId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField IS_CONSISTENCY_FIELD_DESC = new org.apache.thrift.protocol.TField("isConsistency", org.apache.thrift.protocol.TType.BOOL, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new BlockConsitencyCheckTResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new BlockConsitencyCheckTResponseTupleSchemeFactory());
  }

  private long blockId; // required
  private boolean isConsistency; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    BLOCK_ID((short)1, "blockId"),
    IS_CONSISTENCY((short)2, "isConsistency");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BLOCK_ID
          return BLOCK_ID;
        case 2: // IS_CONSISTENCY
          return IS_CONSISTENCY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __BLOCKID_ISSET_ID = 0;
  private static final int __ISCONSISTENCY_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BLOCK_ID, new org.apache.thrift.meta_data.FieldMetaData("blockId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.IS_CONSISTENCY, new org.apache.thrift.meta_data.FieldMetaData("isConsistency", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BlockConsitencyCheckTResponse.class, metaDataMap);
  }

  public BlockConsitencyCheckTResponse() {
  }

  public BlockConsitencyCheckTResponse(
    long blockId,
    boolean isConsistency)
  {
    this();
    this.blockId = blockId;
    setBlockIdIsSet(true);
    this.isConsistency = isConsistency;
    setIsConsistencyIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BlockConsitencyCheckTResponse(BlockConsitencyCheckTResponse other) {
    __isset_bitfield = other.__isset_bitfield;
    this.blockId = other.blockId;
    this.isConsistency = other.isConsistency;
  }

  public BlockConsitencyCheckTResponse deepCopy() {
    return new BlockConsitencyCheckTResponse(this);
  }

  @Override
  public void clear() {
    setBlockIdIsSet(false);
    this.blockId = 0;
    setIsConsistencyIsSet(false);
    this.isConsistency = false;
  }

  public long getBlockId() {
    return this.blockId;
  }

  public BlockConsitencyCheckTResponse setBlockId(long blockId) {
    this.blockId = blockId;
    setBlockIdIsSet(true);
    return this;
  }

  public void unsetBlockId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __BLOCKID_ISSET_ID);
  }

  /** Returns true if field blockId is set (has been assigned a value) and false otherwise */
  public boolean isSetBlockId() {
    return EncodingUtils.testBit(__isset_bitfield, __BLOCKID_ISSET_ID);
  }

  public void setBlockIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __BLOCKID_ISSET_ID, value);
  }

  public boolean isIsConsistency() {
    return this.isConsistency;
  }

  public BlockConsitencyCheckTResponse setIsConsistency(boolean isConsistency) {
    this.isConsistency = isConsistency;
    setIsConsistencyIsSet(true);
    return this;
  }

  public void unsetIsConsistency() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ISCONSISTENCY_ISSET_ID);
  }

  /** Returns true if field isConsistency is set (has been assigned a value) and false otherwise */
  public boolean isSetIsConsistency() {
    return EncodingUtils.testBit(__isset_bitfield, __ISCONSISTENCY_ISSET_ID);
  }

  public void setIsConsistencyIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ISCONSISTENCY_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case BLOCK_ID:
      if (value == null) {
        unsetBlockId();
      } else {
        setBlockId((Long)value);
      }
      break;

    case IS_CONSISTENCY:
      if (value == null) {
        unsetIsConsistency();
      } else {
        setIsConsistency((Boolean)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case BLOCK_ID:
      return getBlockId();

    case IS_CONSISTENCY:
      return isIsConsistency();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case BLOCK_ID:
      return isSetBlockId();
    case IS_CONSISTENCY:
      return isSetIsConsistency();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof BlockConsitencyCheckTResponse)
      return this.equals((BlockConsitencyCheckTResponse)that);
    return false;
  }

  public boolean equals(BlockConsitencyCheckTResponse that) {
    if (that == null)
      return false;

    boolean this_present_blockId = true;
    boolean that_present_blockId = true;
    if (this_present_blockId || that_present_blockId) {
      if (!(this_present_blockId && that_present_blockId))
        return false;
      if (this.blockId != that.blockId)
        return false;
    }

    boolean this_present_isConsistency = true;
    boolean that_present_isConsistency = true;
    if (this_present_isConsistency || that_present_isConsistency) {
      if (!(this_present_isConsistency && that_present_isConsistency))
        return false;
      if (this.isConsistency != that.isConsistency)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_blockId = true;
    list.add(present_blockId);
    if (present_blockId)
      list.add(blockId);

    boolean present_isConsistency = true;
    list.add(present_isConsistency);
    if (present_isConsistency)
      list.add(isConsistency);

    return list.hashCode();
  }

  @Override
  public int compareTo(BlockConsitencyCheckTResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetBlockId()).compareTo(other.isSetBlockId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBlockId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.blockId, other.blockId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIsConsistency()).compareTo(other.isSetIsConsistency());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsConsistency()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isConsistency, other.isConsistency);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("BlockConsitencyCheckTResponse(");
    boolean first = true;

    sb.append("blockId:");
    sb.append(this.blockId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("isConsistency:");
    sb.append(this.isConsistency);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BlockConsitencyCheckTResponseStandardSchemeFactory implements SchemeFactory {
    public BlockConsitencyCheckTResponseStandardScheme getScheme() {
      return new BlockConsitencyCheckTResponseStandardScheme();
    }
  }

  private static class BlockConsitencyCheckTResponseStandardScheme extends StandardScheme<BlockConsitencyCheckTResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BlockConsitencyCheckTResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // BLOCK_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.blockId = iprot.readI64();
              struct.setBlockIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // IS_CONSISTENCY
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.isConsistency = iprot.readBool();
              struct.setIsConsistencyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BlockConsitencyCheckTResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(BLOCK_ID_FIELD_DESC);
      oprot.writeI64(struct.blockId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(IS_CONSISTENCY_FIELD_DESC);
      oprot.writeBool(struct.isConsistency);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BlockConsitencyCheckTResponseTupleSchemeFactory implements SchemeFactory {
    public BlockConsitencyCheckTResponseTupleScheme getScheme() {
      return new BlockConsitencyCheckTResponseTupleScheme();
    }
  }

  private static class BlockConsitencyCheckTResponseTupleScheme extends TupleScheme<BlockConsitencyCheckTResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BlockConsitencyCheckTResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetBlockId()) {
        optionals.set(0);
      }
      if (struct.isSetIsConsistency()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetBlockId()) {
        oprot.writeI64(struct.blockId);
      }
      if (struct.isSetIsConsistency()) {
        oprot.writeBool(struct.isConsistency);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BlockConsitencyCheckTResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.blockId = iprot.readI64();
        struct.setBlockIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.isConsistency = iprot.readBool();
        struct.setIsConsistencyIsSet(true);
      }
    }
  }

}

