/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package alluxio.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)")
public class GetCachePermisionTResponse implements org.apache.thrift.TBase<GetCachePermisionTResponse, GetCachePermisionTResponse._Fields>, java.io.Serializable, Cloneable, Comparable<GetCachePermisionTResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("GetCachePermisionTResponse");

  private static final org.apache.thrift.protocol.TField IS_CACHE_FIELD_DESC = new org.apache.thrift.protocol.TField("isCache", org.apache.thrift.protocol.TType.BOOL, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new GetCachePermisionTResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new GetCachePermisionTResponseTupleSchemeFactory());
  }

  private boolean isCache; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    IS_CACHE((short)1, "isCache");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // IS_CACHE
          return IS_CACHE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ISCACHE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.IS_CACHE, new org.apache.thrift.meta_data.FieldMetaData("isCache", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(GetCachePermisionTResponse.class, metaDataMap);
  }

  public GetCachePermisionTResponse() {
  }

  public GetCachePermisionTResponse(
    boolean isCache)
  {
    this();
    this.isCache = isCache;
    setIsCacheIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public GetCachePermisionTResponse(GetCachePermisionTResponse other) {
    __isset_bitfield = other.__isset_bitfield;
    this.isCache = other.isCache;
  }

  public GetCachePermisionTResponse deepCopy() {
    return new GetCachePermisionTResponse(this);
  }

  @Override
  public void clear() {
    setIsCacheIsSet(false);
    this.isCache = false;
  }

  public boolean isIsCache() {
    return this.isCache;
  }

  public GetCachePermisionTResponse setIsCache(boolean isCache) {
    this.isCache = isCache;
    setIsCacheIsSet(true);
    return this;
  }

  public void unsetIsCache() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ISCACHE_ISSET_ID);
  }

  /** Returns true if field isCache is set (has been assigned a value) and false otherwise */
  public boolean isSetIsCache() {
    return EncodingUtils.testBit(__isset_bitfield, __ISCACHE_ISSET_ID);
  }

  public void setIsCacheIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ISCACHE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case IS_CACHE:
      if (value == null) {
        unsetIsCache();
      } else {
        setIsCache((Boolean)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case IS_CACHE:
      return isIsCache();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case IS_CACHE:
      return isSetIsCache();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof GetCachePermisionTResponse)
      return this.equals((GetCachePermisionTResponse)that);
    return false;
  }

  public boolean equals(GetCachePermisionTResponse that) {
    if (that == null)
      return false;

    boolean this_present_isCache = true;
    boolean that_present_isCache = true;
    if (this_present_isCache || that_present_isCache) {
      if (!(this_present_isCache && that_present_isCache))
        return false;
      if (this.isCache != that.isCache)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_isCache = true;
    list.add(present_isCache);
    if (present_isCache)
      list.add(isCache);

    return list.hashCode();
  }

  @Override
  public int compareTo(GetCachePermisionTResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetIsCache()).compareTo(other.isSetIsCache());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsCache()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isCache, other.isCache);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("GetCachePermisionTResponse(");
    boolean first = true;

    sb.append("isCache:");
    sb.append(this.isCache);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class GetCachePermisionTResponseStandardSchemeFactory implements SchemeFactory {
    public GetCachePermisionTResponseStandardScheme getScheme() {
      return new GetCachePermisionTResponseStandardScheme();
    }
  }

  private static class GetCachePermisionTResponseStandardScheme extends StandardScheme<GetCachePermisionTResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, GetCachePermisionTResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // IS_CACHE
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.isCache = iprot.readBool();
              struct.setIsCacheIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, GetCachePermisionTResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(IS_CACHE_FIELD_DESC);
      oprot.writeBool(struct.isCache);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class GetCachePermisionTResponseTupleSchemeFactory implements SchemeFactory {
    public GetCachePermisionTResponseTupleScheme getScheme() {
      return new GetCachePermisionTResponseTupleScheme();
    }
  }

  private static class GetCachePermisionTResponseTupleScheme extends TupleScheme<GetCachePermisionTResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, GetCachePermisionTResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetIsCache()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetIsCache()) {
        oprot.writeBool(struct.isCache);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, GetCachePermisionTResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.isCache = iprot.readBool();
        struct.setIsCacheIsSet(true);
      }
    }
  }

}

